// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Cla is the golang structure of table cla for DAO operations like Where/Data.
type Cla struct {
	g.Meta    `orm:"table:cla, do:true"`
	Code      interface{} //
	Sid       interface{} // 学校ID
	Cname     interface{} //
	Grade     interface{} //
	Clas      interface{} //
	Mark      interface{} //
	Teacher   interface{} // teacher-mid,
	UpdatedAt *gtime.Time //
	DeletedAt *gtime.Time //
}
