// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Member is the golang structure of table member for DAO operations like Where/Data.
type Member struct {
	g.Meta      `orm:"table:member, do:true"`
	Id          interface{} //
	Username    interface{} //
	Realname    interface{} //
	Nickname    interface{} //
	Idcard      interface{} //
	Group       interface{} //
	Bigclass    interface{} //
	Smallclass  interface{} //
	Mobile      interface{} //
	WebAuth     interface{} //
	Pwd         interface{} //
	Avatar      interface{} //
	Sex         interface{} // 0woman1man
	VerifyType  interface{} //
	VerifyPhoto interface{} //
	VerifyTime  *gtime.Time //
	Status      interface{} // 2dongjie
	Openid      interface{} //
}
