// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysAuthRule is the golang structure of table sys_auth_rule for DAO operations like Where/Data.
type SysAuthRule struct {
	g.Meta    `orm:"table:sys_auth_rule, do:true"`
	Id        interface{} //
	Pid       interface{} // 父ID
	Name      interface{} // 规则名称
	Jump      interface{} //
	Title     interface{} // 规则名称
	Icon      interface{} // 图标
	SmallAuth interface{} // 接口细化权限说明，用来写入casbin第二个权限
	Condition interface{} // 条件：nocheck就不用检测权限
	Remark    interface{} // 备注
	Type      interface{} // 类型1菜单 2接口
	Sort      interface{} // 权重
	IsHide    interface{} // 显示状态
	CreatedAt *gtime.Time // 创建日期
	UpdatedAt *gtime.Time // 修改日期
}
