// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ClaDao is the data access object for table cla.
type ClaDao struct {
	table   string     // table is the underlying table name of the DAO.
	group   string     // group is the database configuration group name of current DAO.
	columns ClaColumns // columns contains all the column names of Table for convenient usage.
}

// ClaColumns defines and stores column names for table cla.
type ClaColumns struct {
	Code      string //
	Sid       string // 学校ID
	Cname     string //
	Grade     string //
	Clas      string //
	Mark      string //
	Teacher   string // teacher-mid,
	UpdatedAt string //
	DeletedAt string //
}

// claColumns holds the columns for table cla.
var claColumns = ClaColumns{
	Code:      "code",
	Sid:       "sid",
	Cname:     "cname",
	Grade:     "grade",
	Clas:      "clas",
	Mark:      "mark",
	Teacher:   "teacher",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
}

// NewClaDao creates and returns a new DAO object for table data access.
func NewClaDao() *ClaDao {
	return &ClaDao{
		group:   "default",
		table:   "cla",
		columns: claColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ClaDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ClaDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ClaDao) Columns() ClaColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ClaDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ClaDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ClaDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
