// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
	"one2.3/internal/model"
	"one2.3/internal/model/entity"
)

type (
	IContext interface {
		Init(r *ghttp.Request, customCtx *model.Context)
		Get(ctx context.Context) *model.Context
		SetUser(ctx context.Context, ctxUser *model.CtxUser)
		SetData(ctx context.Context, data g.Map)
		MInit(r *ghttp.Request, customCtx *entity.Member)
		MGet(ctx context.Context) *entity.Member
	}
)

var (
	localContext IContext
)

func Context() IContext {
	if localContext == nil {
		panic("implement not found for interface IContext, forgot register?")
	}
	return localContext
}

func RegisterContext(i IContext) {
	localContext = i
}
