// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	IMarkdown interface {
		ToHtml(ctx context.Context, md string) (ht string)
	}
)

var (
	localMarkdown IMarkdown
)

func Markdown() IMarkdown {
	if localMarkdown == nil {
		panic("implement not found for interface IMarkdown, forgot register?")
	}
	return localMarkdown
}

func RegisterMarkdown(i IMarkdown) {
	localMarkdown = i
}
