// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"one2.3/internal/model"
)

type (
	IMFile interface {
		Upload(ctx context.Context, in model.FileUploadInput) (*model.FileUploadOutput, error)
	}
)

var (
	localMFile IMFile
)

func MFile() IMFile {
	if localMFile == nil {
		panic("implement not found for interface IMFile, forgot register?")
	}
	return localMFile
}

func RegisterMFile(i IMFile) {
	localMFile = i
}
