// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"one2.3/api/v1/sys"
	"one2.3/internal/model/entity"
)

type (
	IPost interface {
		List(ctx context.Context, req *sys.PostSearchReq) (res *sys.PostSearchRes, err error)
		Add(ctx context.Context, req *sys.PostAddReq) (err error)
		Edit(ctx context.Context, req *sys.PostEditReq) (err error)
		Delete(ctx context.Context, ids []int) (err error)
		GetPost(ctx context.Context) (list []*entity.SysPost, err error)
	}
)

var (
	localPost IPost
)

func Post() IPost {
	if localPost == nil {
		panic("implement not found for interface IPost, forgot register?")
	}
	return localPost
}

func RegisterPost(i IPost) {
	localPost = i
}
