// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/gogf/gf/v2/container/gset"
	"one2.3/api/v1/sys"
)

type (
	IUser interface {
		NotCheckAuthAdminIds(ctx context.Context) *gset.Set
		List(ctx context.Context, req *sys.UserSearchReq) (res *sys.UserSearchRes, err error)
		Add(ctx context.Context, req *sys.UserAddReq) (err error)
		Update(ctx context.Context, req *sys.UserUpdateReq) (err error)
		Delete(ctx context.Context, req *sys.UserDeleteReq) (err error)
		ChangePwd(ctx context.Context, req *sys.UserChangePwdReq) (err error)
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
