// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"one2.3/internal/dao/internal"
)

// internalClaDao is internal type for wrapping internal DAO implements.
type internalClaDao = *internal.ClaDao

// claDao is the data access object for table cla.
// You can define custom methods on it to extend its functionality as you wish.
type claDao struct {
	internalClaDao
}

var (
	// Cla is globally public accessible object for table cla operations.
	Cla = claDao{
		internal.NewClaDao(),
	}
)

// Fill with you ideas below.
