// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"one2.3/internal/dao/internal"
)

// internalMemberDao is internal type for wrapping internal DAO implements.
type internalMemberDao = *internal.MemberDao

// memberDao is the data access object for table member.
// You can define custom methods on it to extend its functionality as you wish.
type memberDao struct {
	internalMemberDao
}

var (
	// Member is globally public accessible object for table member operations.
	Member = memberDao{
		internal.NewMemberDao(),
	}
)

// Fill with you ideas below.
