// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"one2.3/internal/dao/internal"
)

// internalMfileDao is internal type for wrapping internal DAO implements.
type internalMfileDao = *internal.MfileDao

// mfileDao is the data access object for table mfile.
// You can define custom methods on it to extend its functionality as you wish.
type mfileDao struct {
	internalMfileDao
}

var (
	// Mfile is globally public accessible object for table mfile operations.
	Mfile = mfileDao{
		internal.NewMfileDao(),
	}
)

// Fill with you ideas below.
