// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Cla is the golang structure for table cla.
type Cla struct {
	Code      string      `json:"code"      description:""`
	Sid       int         `json:"sid"       description:"学校ID"`
	Cname     string      `json:"cname"     description:""`
	Grade     string      `json:"grade"     description:""`
	Clas      string      `json:"clas"      description:""`
	Mark      string      `json:"mark"      description:""`
	Teacher   string      `json:"teacher"   description:"teacher-mid,"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
	DeletedAt *gtime.Time `json:"deletedAt" description:""`
}
