// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysMenu is the golang structure for table sys_menu.
type SysMenu struct {
	Id        int         `json:"id"        description:""`
	Title     string      `json:"title"     description:"菜单名称"`
	Name      string      `json:"name"      description:""`
	Jump      string      `json:"jump"      description:""`
	Url       string      `json:"url"       description:""`
	Icon      string      `json:"icon"      description:""`
	Remark    string      `json:"remark"    description:""`
	Pid       int         `json:"pid"       description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
	DeletedAt *gtime.Time `json:"deletedAt" description:""`
}
