// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysDept is the golang structure for table sys_dept.
type SysDept struct {
	Id        int64       `json:"id"        description:"部门id"`
	Pid       int64       `json:"pid"       description:"父部门id"`
	Name      string      `json:"name"      description:"部门名称"`
	Sort      int         `json:"sort"      description:"显示顺序"`
	Tel       string      `json:"tel"       description:"联系电话"`
	Email     string      `json:"email"     description:"邮箱"`
	Status    uint        `json:"status"    description:"部门状态（0正常 1停用）"`
	CreatedBy uint64      `json:"createdBy" description:"创建人"`
	UpdatedBy int64       `json:"updatedBy" description:"修改人"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"修改时间"`
	DeletedAt *gtime.Time `json:"deletedAt" description:"删除时间"`
}
