// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysAuthRule is the golang structure for table sys_auth_rule.
type SysAuthRule struct {
	Id        uint        `json:"id"        description:""`
	Pid       uint        `json:"pid"       description:"父ID"`
	Name      string      `json:"name"      description:"规则名称"`
	Jump      string      `json:"jump"      description:""`
	Title     string      `json:"title"     description:"规则名称"`
	Icon      string      `json:"icon"      description:"图标"`
	SmallAuth string      `json:"smallAuth" description:"接口细化权限说明，用来写入casbin第二个权限"`
	Condition string      `json:"condition" description:"条件：nocheck就不用检测权限"`
	Remark    string      `json:"remark"    description:"备注"`
	Type      uint        `json:"type"      description:"类型1菜单 2接口"`
	Sort      int         `json:"sort"      description:"权重"`
	IsHide    uint        `json:"isHide"    description:"显示状态"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建日期"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"修改日期"`
}
